let a = 3;
let b = 5;
let c = 8;
let adicao = a + b;
//console.log(adicao);
let subtracao = a - b;
//console.log(subtracao);
let multiplicacao = a * b;
//console.log(multiplicacao);
let divisao = a / b;
//console.log(divisao);
let modulo = a % b;
//console.log(modulo);
console.log(adicao, subtracao, multiplicacao, divisao, modulo);
